#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Delete Lines Python Script

from sys import argv, stdout # Imports arguments and stdout from sys

oldFile = argv[1] # The path for the file we want to modify
newFile = argv[2]
find = argv[3:] # The array of different strings we want to look for (every argument after the first one)

n = open(newFile,"w") # Open new file in write mode

for string in find:            # For every string passed in and
    for line in open(oldFile): # For every line in the old file
        if string not in line: # Check for string
            n.write(line)      # If it exists, don't write it to new file.

n.close() # Close the new file

printFind = "[{0}]".format(", ".join(str(i) for i in find))
print("\rDeleted every line that contained "+printFind+" output to file: "+newFile)